
--------------------------------------------------------------
-- Database creation Script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- Verbose generation: ON

-- note: spaces within table/column names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :

-- To drop the tables generated by this script run -
--   'C:\Users\Maive\SynologyDrive\Kool\Magister\Andmebaasid\Iseseisev_yl\sql_AUTOMAATNE_drop.sql'

--------------------------------------------------------------



--------------------------------------------------------------
-- Table Creation --

-- Each entity on the model is represented by a table that needs to be created within the Database.
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.

-- Create a Database table to represent the "KLIENDILEPING" entity.
CREATE TABLE KLIENDILEPING(
	kliendileping_ID	INTEGER NOT NULL,
	isik_ID	INTEGER NOT NULL,
	firma_ID	INTEGER,
	alates	DATE NOT NULL,
	kuni	DATE,
	lepingu_nr	VARCHAR(25) NOT NULL,
	fk1_isik_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "KLIENDILEPING".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_KLIENDILEPING PRIMARY KEY (kliendileping_ID)
);

-- Create a Database table to represent the "KASUTAJAKONTO" entity.
CREATE TABLE KASUTAJAKONTO(
	kasutajakonto_ID	INTEGER NOT NULL,
	isik_ID	INTEGER NOT NULL,
	kliendileping_ID	INTEGER NOT NULL,
	kasutajanimi	VARCHAR(25) NOT NULL,
	parool	VARCHAR(25) NOT NULL,
	fk1_kliendileping_ID	INTEGER NOT NULL,
	fk2_isik_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "KASUTAJAKONTO".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_KASUTAJAKONTO PRIMARY KEY (kasutajakonto_ID)
);

-- Create a Database table to represent the "ISIK" entity.
CREATE TABLE ISIK(
	isik_ID	INTEGER NOT NULL,
	isiku_liik_ID	INTEGER NOT NULL,
	eesnimi	VARCHAR(25) NOT NULL,
	perenimi	VARCHAR(25) NOT NULL,
	isikukood	VARCHAR(11),
	aadress	VARCHAR(100),
	telefoni_nr	VARCHAR(20),
	email	VARCHAR(40),
	synniaeg	DATE,
	fk1_isiku_liik_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "ISIK".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_ISIK PRIMARY KEY (isik_ID)
);

-- Create a Database table to represent the "FIRMA" entity.
CREATE TABLE FIRMA(
	firma_ID	INTEGER NOT NULL,
	registri_nr	VARCHAR(8) NOT NULL,
	nimi	VARCHAR(8) NOT NULL,
	aadress	VARCHAR(8),
	kontaktisik	VARCHAR(8),
	kontakt_telefon	VARCHAR(8) NOT NULL,
	kontakt_email	VARCHAR(8) NOT NULL,
	luhinimi	VARCHAR(8),
	-- Specify the PRIMARY KEY constraint for table "FIRMA".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_FIRMA PRIMARY KEY (firma_ID)
);

-- Create a Database table to represent the "KASUTAJAK_ROLL" entity.
CREATE TABLE KASUTAJAK_ROLL(
	kasutajak_roll_ID	INTEGER NOT NULL,
	kasutajakonto_ID	INTEGER NOT NULL,
	roll_ID	INTEGER NOT NULL,
	alates	DATE NOT NULL,
	kuni	DATE NOT NULL,
	fk1_kasutajakonto_ID	INTEGER NOT NULL,
	fk2_roll_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "KASUTAJAK_ROLL".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_KASUTAJAK_ROLL PRIMARY KEY (kasutajak_roll_ID)
);

-- Create a Database table to represent the "ROLL" entity.
CREATE TABLE ROLL(
	roll_ID	INTEGER NOT NULL,
	nimetus	VARCHAR(25) NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "ROLL".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_ROLL PRIMARY KEY (roll_ID)
);

-- Create a Database table to represent the "ROLLI_TEGEVUS" entity.
CREATE TABLE ROLLI_TEGEVUS(
	rolli_tegevus_ID	INTEGER NOT NULL,
	roll_ID	INTEGER NOT NULL,
	tegevus_ID	INTEGER NOT NULL,
	alates	DATE NOT NULL,
	kuni	DATE,
	fk1_roll_ID	INTEGER NOT NULL,
	fk2_tegevus_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "ROLLI_TEGEVUS".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_ROLLI_TEGEVUS PRIMARY KEY (rolli_tegevus_ID)
);

-- Create a Database table to represent the "TEGEVUS" entity.
CREATE TABLE TEGEVUS(
	tegevus_ID	INTEGER NOT NULL,
	tegevus_ID_ylem	INTEGER,
	nimetus	VARCHAR(25) NOT NULL,
	kirjeldus	LONG VARCHAR,
	-- Specify the PRIMARY KEY constraint for table "TEGEVUS".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_TEGEVUS PRIMARY KEY (tegevus_ID)
);

-- Create a Database table to represent the "ERIHIND_KL_LEPINGUS" entity.
CREATE TABLE ERIHIND_KL_LEPINGUS(
	erihind_kl_lepingus_ID	INTEGER NOT NULL,
	kliendileping_ID	INTEGER NOT NULL,
	erihind_ID	INTEGER NOT NULL,
	alates	DATE NOT NULL,
	kuni	DATE,
	fk1_kliendileping_ID	INTEGER NOT NULL,
	fk2_erihind_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "ERIHIND_KL_LEPINGUS".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_ERIHIND_KL_LEPINGUS PRIMARY KEY (erihind_kl_lepingus_ID)
);

-- Create a Database table to represent the "ERIHIND" entity.
CREATE TABLE ERIHIND(
	erihind_ID	INTEGER NOT NULL,
	testi_nimi	VARCHAR(25) NOT NULL,
	kogus_alates	INTEGER NOT NULL,
	kogus_kuni	INTEGER,
	allahindluse_protsent	DECIMAL(8,2) NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "ERIHIND".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_ERIHIND PRIMARY KEY (erihind_ID)
);

-- Create a Database table to represent the "TELLIMUS" entity.
CREATE TABLE TELLIMUS(
	tellimus_ID	INTEGER NOT NULL,
	kliendileping_ID	INTEGER NOT NULL,
	tellimuse_nr	VARCHAR(8),
	summa_kmta	DECIMAL(8,2) NOT NULL,
	kaibemaks_kokku	DECIMAL(8,2) NOT NULL,
	summa_kokku	DECIMAL(8,2) NOT NULL,
	aeg	TIMESTAMP(8) NOT NULL,
	fk1_kliendileping_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "TELLIMUS".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_TELLIMUS PRIMARY KEY (tellimus_ID)
);

-- Create a Database table to represent the "TELLIMUSE_RIDA" entity.
CREATE TABLE TELLIMUSE_RIDA(
	tellimuse_rida_ID	INTEGER NOT NULL,
	tellimuse_ID	INTEGER NOT NULL,
	test_tellimuses_ID	INTEGER NOT NULL,
	kampaania_ID	INTEGER,
	erihind_kl_lepingus_ID	INTEGER,
	kogus	INTEGER NOT NULL,
	hind_kmta	DECIMAL(8,2),
	kaibemaks	DECIMAL(8,2) NOT NULL,
	hind_kmga	DECIMAL(8,2),
	fk1_tellimus_ID	INTEGER NOT NULL,
	fk2_test_tellimuses_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "TELLIMUSE_RIDA".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_TELLIMUSE_RIDA PRIMARY KEY (tellimuse_rida_ID)
);

-- Create a Database table to represent the "TEST_TELLIMUSES" entity.
CREATE TABLE TEST_TELLIMUSES(
	test_tellimuses_ID	INTEGER NOT NULL,
	test_ID	INTEGER NOT NULL,
	proov_ID	INTEGER NOT NULL,
	isik_ID_testi_teostaja	INTEGER NOT NULL,
	tulemus_ID	INTEGER,
	fk1_test_ID	INTEGER NOT NULL,
	fk2_isik_ID	INTEGER NOT NULL,
	fk3_proov_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "TEST_TELLIMUSES".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_TEST_TELLIMUSES PRIMARY KEY (test_tellimuses_ID)
);

-- Create a Database table to represent the "VAHEND" entity.
CREATE TABLE VAHEND(
	vahend_ID	INTEGER NOT NULL,
	vahendi_tyyp_ID	INTEGER NOT NULL,
	nimetus	VARCHAR(60) NOT NULL,
	LOT_nr	VARCHAR(20),
	saabumise_aeg	TIMESTAMP(8),
	karbi_nr	INTEGER,
	seadme_kood	VARCHAR(25),
	fk1_vahendi_tyyp_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "VAHEND".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_VAHEND PRIMARY KEY (vahend_ID)
);

-- Create a Database table to represent the "PROOV" entity.
CREATE TABLE PROOV(
	proov_ID	INTEGER NOT NULL,
	proovi_tyyp_ID	INTEGER NOT NULL,
	isik_ID_proovi_andja	INTEGER NOT NULL,
	isik_ID_proovi_votja	INTEGER NOT NULL,
	votmise_aeg	DATE NOT NULL,
	fk1_proovi_tyyp_ID	INTEGER NOT NULL,
	fk2_isik_ID	INTEGER NOT NULL,
	fk3_isik_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "PROOV".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_PROOV PRIMARY KEY (proov_ID)
);

-- Create a Database table to represent the "TULEMUS" entity.
CREATE TABLE TULEMUS(
	tulemus_ID	INTEGER NOT NULL,
	tulemus	VARCHAR(100) NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "TULEMUS".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_TULEMUS PRIMARY KEY (tulemus_ID)
);

-- Create a Database table to represent the "HIND" entity.
CREATE TABLE HIND(
	hind_ID	INTEGER NOT NULL,
	test_ID	INTEGER NOT NULL,
	kampaania_ID	INTEGER,
	erihind_kl_lepingus_ID	INTEGER,
	hind	DECIMAL(8,2) NOT NULL,
	valuuta	VARCHAR(10) NOT NULL,
	fk1_test_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "HIND".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_HIND PRIMARY KEY (hind_ID)
);

-- Create a Database table to represent the "VAHENDI_TYYP" entity.
CREATE TABLE VAHENDI_TYYP(
	vahendi_tyyp_ID	INTEGER NOT NULL,
	tyybi_nimetus	VARCHAR(60) NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "VAHENDI_TYYP".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_VAHENDI_TYYP PRIMARY KEY (vahendi_tyyp_ID)
);

-- Create a Database table to represent the "KASUTATUD_VAHEND" entity.
CREATE TABLE KASUTATUD_VAHEND(
	kasutatud_vahend_ID	INTEGER NOT NULL,
	test_tellimuses_ID	INTEGER NOT NULL,
	vahend_ID	INTEGER NOT NULL,
	kasutamise_aeg	TIMESTAMP(8) NOT NULL,
	fk1_test_tellimuses_ID	INTEGER NOT NULL,
	fk2_vahend_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "KASUTATUD_VAHEND".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_KASUTATUD_VAHEND PRIMARY KEY (kasutatud_vahend_ID)
);

-- Create a Database table to represent the "SEADE_PARANDUSES" entity.
CREATE TABLE SEADE_PARANDUSES(
	seade_paranduses_ID	INTEGER NOT NULL,
	vahend_ID	INTEGER NOT NULL,
	alates	DATE NOT NULL,
	kuni	DATE,
	fk1_vahend_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "SEADE_PARANDUSES".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_SEADE_PARANDUSES PRIMARY KEY (seade_paranduses_ID)
);

-- Create a Database table to represent the "TEST" entity.
CREATE TABLE TEST(
	test_ID	INTEGER NOT NULL,
	nimetus	VARCHAR(60) NOT NULL,
	kirjeldus	LONG VARCHAR,
	-- Specify the PRIMARY KEY constraint for table "TEST".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_TEST PRIMARY KEY (test_ID)
);

-- Create a Database table to represent the "TOOGRAAFIK" entity.
CREATE TABLE TOOGRAAFIK(
	toograafik_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "TOOGRAAFIK".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_TOOGRAAFIK PRIMARY KEY (toograafik_ID)
);

-- Create a Database table to represent the "TOOTAJA_GRAAFIKUS" entity.
CREATE TABLE TOOTAJA_GRAAFIKUS(
	tootaja_graafikus_ID	INTEGER NOT NULL,
	isik_ID	INTEGER NOT NULL,
	positsioon	INTEGER NOT NULL,
	alates	TIMESTAMP(8) NOT NULL,
	kuni	TIMESTAMP(8) NOT NULL,
	fk1_toograafik_ID	INTEGER NOT NULL,
	fk2_positsioon_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "TOOTAJA_GRAAFIKUS".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_TOOTAJA_GRAAFIKUS PRIMARY KEY (tootaja_graafikus_ID)
);

-- Create a Database table to represent the "POSITSIOON" entity.
CREATE TABLE POSITSIOON(
	positsioon_ID	INTEGER NOT NULL,
	nimetus	VARCHAR(25) NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "POSITSIOON".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_POSITSIOON PRIMARY KEY (positsioon_ID)
);

-- Create a Database table to represent the "KAMPAANIA" entity.
CREATE TABLE KAMPAANIA(
	kampaania_ID	INTEGER NOT NULL,
	test_ID	INTEGER NOT NULL,
	kampaania_nimi	VARCHAR(8) NOT NULL,
	allahindluse_protsent	DECIMAL(8,2) NOT NULL,
	algus	TIME(8) NOT NULL,
	lopp	TIME(8) NOT NULL,
	fk1_test_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "KAMPAANIA".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_KAMPAANIA PRIMARY KEY (kampaania_ID)
);

-- Create a Database table to represent the "ISIKU_LIIK" entity.
CREATE TABLE ISIKU_LIIK(
	isiku_liik_ID	INTEGER NOT NULL,
	nimetus	VARCHAR(25) NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "ISIKU_LIIK".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_ISIKU_LIIK PRIMARY KEY (isiku_liik_ID)
);

-- Create a Database table to represent the "PROOVI_TYYP" entity.
CREATE TABLE PROOVI_TYYP(
	proovi_tyyp_ID	INTEGER NOT NULL,
	nimetus	VARCHAR(25) NOT NULL,
	sailitustngmsd	LONG VARCHAR NOT NULL,
	kirjedus	LONG VARCHAR,
	-- Specify the PRIMARY KEY constraint for table "PROOVI_TYYP".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_PROOVI_TYYP PRIMARY KEY (proovi_tyyp_ID)
);


--------------------------------------------------------------
-- Create LINK tables --

-- These tables do not appear as entities on the model. The reason they are created
-- is to allow certain types of relationships to be implemented in a Relational type Database.
-- Each link table tends to represent a specific relationship that appears on the model.
-- The attributes contained in link tables are identified from the entities at either side
-- of the relationship. i.e. they do not define attributes in their own right.
-- Indeed foreign key constraints are always created to ensure referential integrity between the
-- link table attributes and the primary key attributes on which they are based.

-- Create a link table to represent the "FIRMA_KLIENDILEPING" relationship.
-- The attributes of this table are taken from the primary keys of table "FIRMA" and
-- table "KLIENDILEPING", i.e. each end of the relationship. A link table was created
-- because "FIRMA_KLIENDILEPING" is a one to many relationship with optionality at the one side.
-- notice how the primary key is only based on the key of the table at the many side, i.e. table "KLIENDILEPING".
CREATE TABLE FIRMA_KLIENDILEPING(
	s_firma_ID	INTEGER NOT NULL,
	d_kliendileping_ID	INTEGER NOT NULL,
	PRIMARY KEY (d_kliendileping_ID),
	FOREIGN KEY(s_firma_ID) REFERENCES FIRMA(firma_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(d_kliendileping_ID) REFERENCES KLIENDILEPING(kliendileping_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Create a link table to represent the "TEGEVUS_TEGEVUS" relationship.
-- The attributes of this table are taken from the primary keys of table "TEGEVUS" and
-- table "TEGEVUS", i.e. each end of the relationship. A link table was created
-- because "TEGEVUS_TEGEVUS" is a one to many relationship with optionality at the one side.
-- notice how the primary key is only based on the key of the table at the many side, i.e. table "TEGEVUS".
CREATE TABLE TEGEVUS_TEGEVUS(
	s_tegevus_ID	INTEGER NOT NULL,
	d_tegevus_ID	INTEGER NOT NULL,
	PRIMARY KEY (d_tegevus_ID),
	FOREIGN KEY(s_tegevus_ID) REFERENCES TEGEVUS(tegevus_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(d_tegevus_ID) REFERENCES TEGEVUS(tegevus_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Create a link table to represent the "KAMPAANIA_HIND" relationship.
-- The attributes of this table are taken from the primary keys of table "KAMPAANIA" and
-- table "HIND", i.e. each end of the relationship. A link table was created
-- because "KAMPAANIA_HIND" is a one to many relationship with optionality at the one side.
-- notice how the primary key is only based on the key of the table at the many side, i.e. table "HIND".
CREATE TABLE KAMPAANIA_HIND(
	s_kampaania_ID	INTEGER NOT NULL,
	d_hind_ID	INTEGER NOT NULL,
	PRIMARY KEY (d_hind_ID),
	FOREIGN KEY(s_kampaania_ID) REFERENCES KAMPAANIA(kampaania_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(d_hind_ID) REFERENCES HIND(hind_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Create a link table to represent the "TULEMUS_TEST_TELLIMUSES" relationship.
-- The attributes of this table are taken from the primary keys of table "TULEMUS" and
-- table "TEST_TELLIMUSES", i.e. each end of the relationship. A link table was created
-- because "TULEMUS_TEST_TELLIMUSES" is a one to many relationship with optionality at the one side.
-- notice how the primary key is only based on the key of the table at the many side, i.e. table "TEST_TELLIMUSES".
CREATE TABLE TULEMUS_TEST_TELLIMUSES(
	s_tulemus_ID	INTEGER NOT NULL,
	d_test_tellimuses_ID	INTEGER NOT NULL,
	PRIMARY KEY (d_test_tellimuses_ID),
	FOREIGN KEY(s_tulemus_ID) REFERENCES TULEMUS(tulemus_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(d_test_tellimuses_ID) REFERENCES TEST_TELLIMUSES(test_tellimuses_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Create a link table to represent the "ERIHIND_KL_LEPINGUS_HIND" relationship.
-- The attributes of this table are taken from the primary keys of table "ERIHIND_KL_LEPINGUS" and
-- table "HIND", i.e. each end of the relationship. A link table was created
-- because "ERIHIND_KL_LEPINGUS_HIND" is a one to many relationship with optionality at the one side.
-- notice how the primary key is only based on the key of the table at the many side, i.e. table "HIND".
CREATE TABLE ERIHIND_KL_LEPINGUS_HIND(
	s_erihind_kl_lepingus_ID	INTEGER NOT NULL,
	d_hind_ID	INTEGER NOT NULL,
	PRIMARY KEY (d_hind_ID),
	FOREIGN KEY(s_erihind_kl_lepingus_ID) REFERENCES ERIHIND_KL_LEPINGUS(erihind_kl_lepingus_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(d_hind_ID) REFERENCES HIND(hind_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Create a link table to represent the "KAMPAANIA_TELLIMUSE_RIDA" relationship.
-- The attributes of this table are taken from the primary keys of table "KAMPAANIA" and
-- table "TELLIMUSE_RIDA", i.e. each end of the relationship. A link table was created
-- because "KAMPAANIA_TELLIMUSE_RIDA" is a one to many relationship with optionality at the one side.
-- notice how the primary key is only based on the key of the table at the many side, i.e. table "TELLIMUSE_RIDA".
CREATE TABLE KAMPAANIA_TELLIMUSE_RIDA(
	s_kampaania_ID	INTEGER NOT NULL,
	d_tellimuse_rida_ID	INTEGER NOT NULL,
	PRIMARY KEY (d_tellimuse_rida_ID),
	FOREIGN KEY(s_kampaania_ID) REFERENCES KAMPAANIA(kampaania_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(d_tellimuse_rida_ID) REFERENCES TELLIMUSE_RIDA(tellimuse_rida_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- Create a link table to represent the "ERIHIND_KL_LEPINGUS_TELLIMUSE_RIDA" relationship.
-- The attributes of this table are taken from the primary keys of table "ERIHIND_KL_LEPINGUS" and
-- table "TELLIMUSE_RIDA", i.e. each end of the relationship. A link table was created
-- because "ERIHIND_KL_LEPINGUS_TELLIMUSE_RIDA" is a one to many relationship with optionality at the one side.
-- notice how the primary key is only based on the key of the table at the many side, i.e. table "TELLIMUSE_RIDA".
CREATE TABLE ERIHIND_KL_LEPINGUS_TELLIMUSE_RIDA(
	s_erihind_kl_lepingus_ID	INTEGER NOT NULL,
	d_tellimuse_rida_ID	INTEGER NOT NULL,
	PRIMARY KEY (d_tellimuse_rida_ID),
	FOREIGN KEY(s_erihind_kl_lepingus_ID) REFERENCES ERIHIND_KL_LEPINGUS(erihind_kl_lepingus_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(d_tellimuse_rida_ID) REFERENCES TELLIMUSE_RIDA(tellimuse_rida_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);


--------------------------------------------------------------
-- Alter Tables to add fk constraints --

-- Now all the tables have been created the ALTER TABLE command is used to define some additional
-- constraints.  These typically constrain values of foreign keys to be associated in some way
-- with the primary keys of related tables.  Foreign key constraints can actually be specified
-- when each table is created, but doing so can lead to dependency problems within the script
-- i.e. tables may be referenced before they have been created.  This method is therefore safer.

-- Alter table to add new constraints required to implement the "KLIENDILEPING_ISIK" relationship

-- This constraint ensures that the foreign key of table "KLIENDILEPING"
-- correctly references the primary key of table "ISIK"

ALTER TABLE KLIENDILEPING ADD CONSTRAINT fk1_KLIENDILEPING_to_ISIK FOREIGN KEY(fk1_isik_ID) REFERENCES ISIK(isik_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "KASUTAJAKONTO_KLIENDILEPING" relationship

-- This constraint ensures that the foreign key of table "KASUTAJAKONTO"
-- correctly references the primary key of table "KLIENDILEPING"

ALTER TABLE KASUTAJAKONTO ADD CONSTRAINT fk1_KASUTAJAKONTO_to_KLIENDILEPING FOREIGN KEY(fk1_kliendileping_ID) REFERENCES KLIENDILEPING(kliendileping_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "KASUTAJAKONTO_ISIK" relationship

-- This constraint ensures that the foreign key of table "KASUTAJAKONTO"
-- correctly references the primary key of table "ISIK"

ALTER TABLE KASUTAJAKONTO ADD CONSTRAINT fk2_KASUTAJAKONTO_to_ISIK FOREIGN KEY(fk2_isik_ID) REFERENCES ISIK(isik_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "KASUTAJAK_ROLL_KASUTAJAKONTO" relationship

-- This constraint ensures that the foreign key of table "KASUTAJAK_ROLL"
-- correctly references the primary key of table "KASUTAJAKONTO"

ALTER TABLE KASUTAJAK_ROLL ADD CONSTRAINT fk1_KASUTAJAK_ROLL_to_KASUTAJAKONTO FOREIGN KEY(fk1_kasutajakonto_ID) REFERENCES KASUTAJAKONTO(kasutajakonto_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "KASUTAJAK_ROLL_ROLL" relationship

-- This constraint ensures that the foreign key of table "KASUTAJAK_ROLL"
-- correctly references the primary key of table "ROLL"

ALTER TABLE KASUTAJAK_ROLL ADD CONSTRAINT fk2_KASUTAJAK_ROLL_to_ROLL FOREIGN KEY(fk2_roll_ID) REFERENCES ROLL(roll_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "ROLLI_TEGEVUS_ROLL" relationship

-- This constraint ensures that the foreign key of table "ROLLI_TEGEVUS"
-- correctly references the primary key of table "ROLL"

ALTER TABLE ROLLI_TEGEVUS ADD CONSTRAINT fk1_ROLLI_TEGEVUS_to_ROLL FOREIGN KEY(fk1_roll_ID) REFERENCES ROLL(roll_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "ROLLI_TEGEVUS_TEGEVUS" relationship

-- This constraint ensures that the foreign key of table "ROLLI_TEGEVUS"
-- correctly references the primary key of table "TEGEVUS"

ALTER TABLE ROLLI_TEGEVUS ADD CONSTRAINT fk2_ROLLI_TEGEVUS_to_TEGEVUS FOREIGN KEY(fk2_tegevus_ID) REFERENCES TEGEVUS(tegevus_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "ERIHIND_KL_LEPINGUS_KLIENDILEPING" relationship

-- This constraint ensures that the foreign key of table "ERIHIND_KL_LEPINGUS"
-- correctly references the primary key of table "KLIENDILEPING"

ALTER TABLE ERIHIND_KL_LEPINGUS ADD CONSTRAINT fk1_ERIHIND_KL_LEPINGUS_to_KLIENDILEPING FOREIGN KEY(fk1_kliendileping_ID) REFERENCES KLIENDILEPING(kliendileping_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "ERIHIND_KL_LEPINGUS_ERIHIND" relationship

-- This constraint ensures that the foreign key of table "ERIHIND_KL_LEPINGUS"
-- correctly references the primary key of table "ERIHIND"

ALTER TABLE ERIHIND_KL_LEPINGUS ADD CONSTRAINT fk2_ERIHIND_KL_LEPINGUS_to_ERIHIND FOREIGN KEY(fk2_erihind_ID) REFERENCES ERIHIND(erihind_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "TELLIMUS_KLIENDILEPING" relationship

-- This constraint ensures that the foreign key of table "TELLIMUS"
-- correctly references the primary key of table "KLIENDILEPING"

ALTER TABLE TELLIMUS ADD CONSTRAINT fk1_TELLIMUS_to_KLIENDILEPING FOREIGN KEY(fk1_kliendileping_ID) REFERENCES KLIENDILEPING(kliendileping_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "TELLIMUSE_RIDA_TELLIMUS" relationship

-- This constraint ensures that the foreign key of table "TELLIMUSE_RIDA"
-- correctly references the primary key of table "TELLIMUS"

ALTER TABLE TELLIMUSE_RIDA ADD CONSTRAINT fk1_TELLIMUSE_RIDA_to_TELLIMUS FOREIGN KEY(fk1_tellimus_ID) REFERENCES TELLIMUS(tellimus_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "TELLIMUSE_RIDA_TEST_TELLIMUSES" relationship

-- This constraint ensures that the foreign key of table "TELLIMUSE_RIDA"
-- correctly references the primary key of table "TEST_TELLIMUSES"

ALTER TABLE TELLIMUSE_RIDA ADD CONSTRAINT fk2_TELLIMUSE_RIDA_to_TEST_TELLIMUSES FOREIGN KEY(fk2_test_tellimuses_ID) REFERENCES TEST_TELLIMUSES(test_tellimuses_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "VAHEND_VAHENDI_TYYP" relationship

-- This constraint ensures that the foreign key of table "VAHEND"
-- correctly references the primary key of table "VAHENDI_TYYP"

ALTER TABLE VAHEND ADD CONSTRAINT fk1_VAHEND_to_VAHENDI_TYYP FOREIGN KEY(fk1_vahendi_tyyp_ID) REFERENCES VAHENDI_TYYP(vahendi_tyyp_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "KASUTATUD_VAHEND_TEST_TELLIMUSES" relationship

-- This constraint ensures that the foreign key of table "KASUTATUD_VAHEND"
-- correctly references the primary key of table "TEST_TELLIMUSES"

ALTER TABLE KASUTATUD_VAHEND ADD CONSTRAINT fk1_KASUTATUD_VAHEND_to_TEST_TELLIMUSES FOREIGN KEY(fk1_test_tellimuses_ID) REFERENCES TEST_TELLIMUSES(test_tellimuses_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "KASUTATUD_VAHEND_VAHEND" relationship

-- This constraint ensures that the foreign key of table "KASUTATUD_VAHEND"
-- correctly references the primary key of table "VAHEND"

ALTER TABLE KASUTATUD_VAHEND ADD CONSTRAINT fk2_KASUTATUD_VAHEND_to_VAHEND FOREIGN KEY(fk2_vahend_ID) REFERENCES VAHEND(vahend_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "SEADE_PARANDUSES_VAHEND" relationship

-- This constraint ensures that the foreign key of table "SEADE_PARANDUSES"
-- correctly references the primary key of table "VAHEND"

ALTER TABLE SEADE_PARANDUSES ADD CONSTRAINT fk1_SEADE_PARANDUSES_to_VAHEND FOREIGN KEY(fk1_vahend_ID) REFERENCES VAHEND(vahend_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "TEST_TELLIMUSES_TEST" relationship

-- This constraint ensures that the foreign key of table "TEST_TELLIMUSES"
-- correctly references the primary key of table "TEST"

ALTER TABLE TEST_TELLIMUSES ADD CONSTRAINT fk1_TEST_TELLIMUSES_to_TEST FOREIGN KEY(fk1_test_ID) REFERENCES TEST(test_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "TEST_TELLIMUSES_ISIK" relationship

-- This constraint ensures that the foreign key of table "TEST_TELLIMUSES"
-- correctly references the primary key of table "ISIK"

ALTER TABLE TEST_TELLIMUSES ADD CONSTRAINT fk2_TEST_TELLIMUSES_to_ISIK FOREIGN KEY(fk2_isik_ID) REFERENCES ISIK(isik_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "TOOTAJA_GRAAFIKUS_TOOGRAAFIK" relationship

-- This constraint ensures that the foreign key of table "TOOTAJA_GRAAFIKUS"
-- correctly references the primary key of table "TOOGRAAFIK"

ALTER TABLE TOOTAJA_GRAAFIKUS ADD CONSTRAINT fk1_TOOTAJA_GRAAFIKUS_to_TOOGRAAFIK FOREIGN KEY(fk1_toograafik_ID) REFERENCES TOOGRAAFIK(toograafik_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "TOOTAJA_GRAAFIKUS_POSITSIOON" relationship

-- This constraint ensures that the foreign key of table "TOOTAJA_GRAAFIKUS"
-- correctly references the primary key of table "POSITSIOON"

ALTER TABLE TOOTAJA_GRAAFIKUS ADD CONSTRAINT fk2_TOOTAJA_GRAAFIKUS_to_POSITSIOON FOREIGN KEY(fk2_positsioon_ID) REFERENCES POSITSIOON(positsioon_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "HIND_TEST" relationship

-- This constraint ensures that the foreign key of table "HIND"
-- correctly references the primary key of table "TEST"

ALTER TABLE HIND ADD CONSTRAINT fk1_HIND_to_TEST FOREIGN KEY(fk1_test_ID) REFERENCES TEST(test_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "ISIK_ISIKU_LIIK" relationship

-- This constraint ensures that the foreign key of table "ISIK"
-- correctly references the primary key of table "ISIKU_LIIK"

ALTER TABLE ISIK ADD CONSTRAINT fk1_ISIK_to_ISIKU_LIIK FOREIGN KEY(fk1_isiku_liik_ID) REFERENCES ISIKU_LIIK(isiku_liik_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "PROOV_PROOVI_TYYP" relationship

-- This constraint ensures that the foreign key of table "PROOV"
-- correctly references the primary key of table "PROOVI_TYYP"

ALTER TABLE PROOV ADD CONSTRAINT fk1_PROOV_to_PROOVI_TYYP FOREIGN KEY(fk1_proovi_tyyp_ID) REFERENCES PROOVI_TYYP(proovi_tyyp_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "TEST_TELLIMUSES_PROOV" relationship

-- This constraint ensures that the foreign key of table "TEST_TELLIMUSES"
-- correctly references the primary key of table "PROOV"

ALTER TABLE TEST_TELLIMUSES ADD CONSTRAINT fk3_TEST_TELLIMUSES_to_PROOV FOREIGN KEY(fk3_proov_ID) REFERENCES PROOV(proov_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "PROOV_ISIK" relationship

-- This constraint ensures that the foreign key of table "PROOV"
-- correctly references the primary key of table "ISIK"

ALTER TABLE PROOV ADD CONSTRAINT fk2_PROOV_to_ISIK FOREIGN KEY(fk2_isik_ID) REFERENCES ISIK(isik_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "PROOV_ISIK" relationship

-- This constraint ensures that the foreign key of table "PROOV"
-- correctly references the primary key of table "ISIK"

ALTER TABLE PROOV ADD CONSTRAINT fk3_PROOV_to_ISIK FOREIGN KEY(fk3_isik_ID) REFERENCES ISIK(isik_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "KAMPAANIA_TEST" relationship

-- This constraint ensures that the foreign key of table "KAMPAANIA"
-- correctly references the primary key of table "TEST"

ALTER TABLE KAMPAANIA ADD CONSTRAINT fk1_KAMPAANIA_to_TEST FOREIGN KEY(fk1_test_ID) REFERENCES TEST(test_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


--------------------------------------------------------------
-- End of DDL file auto-generation
--------------------------------------------------------------
